spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog
    username: root
    password: qazwsxedc123..
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    database: 13
    host: localhost
    password: qazwsxedc123..
    lettuce:
      pool:
        max-idle: 16
        max-active: 32
        min-idle: 8
  rabbitmq:
    host: localhost
    port: 5672
    username: lidengxiang
    password: qazwsxedc123..
    publisher-confirm-type: correlated #开启发布确认.默认是关闭的
    publisher-returns: true # 开启消息回退,交换机找不到队列,会直接丢弃消息,会退给生产者
  mail:
    port: 587
    username: 495234450@qq.com
    password: pcntfvodanjibgjd
    host: smtp.qq.com
    properties:
      mail:
        smtp:
          ssl:
            enable: true
files:
  path: /files
redirect:
  url: "https://www.lidengxiang.top/#/loading/"
  error-page: "https://www.lidengxiang.top/#/login/"

project:
  version: 1.0.0

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  pattern:
    console: '%clr(%d{yyyyMMdd HH:mm:ss}){yellow} [%clr(%thread){red}] %-5level --- %clr(%logger){blue} | %msg%n'